### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by zhiga90** [wangpin34/vue-scroll#29]
https://www.webpackbin.com/bins/-L25UF-5tGsRqXjGvPf6
directive is not working

**Comment by wangpin34** [comment]
@zhiga90 因为你没有在 ul 上滚动。尝试设置 ul 为固定高度。

```css
  ul {
   height: 200px;
   overflow: auto;
  } 
```
此时， ul 内部出现滚动条，拖动滚动条，或者使用鼠标中键，你会看到 vue-scroll 开始工作了。
